[AudioUnit] Fix csc compiler error not allowing unsafe code in iterators. (#2386)
csc does not allow unsafe code in iterators:

AudioUnit/AudioUnit.cs(1725,13): error CS1629: Unsafe code may not appear in iterators
AudioUnit/AudioUnit.cs(1725,33): error CS1629: Unsafe code may not appear in iterators
AudioUnit/AudioUnit.cs(1723,19): error CS1629: Unsafe code may not appear in iterators

It looks like mcs incorrectly allows this (https://bugzilla.xamarin.com/show_bug.cgi?id=56616).

So change the code to remove unsafe usage in iterators.
(cherry picked from commit aab8060d29aeac2da33d362fa406cf1403ce766c)